[?1049h[22;0;0t[>4;2m[?1h=[?2004h[?1004h[1;23r[?12h[?12l[22;2t[22;1t[27m[23m[29m[m[H[2J[?25l[23;1H"/tmp/kubectl-edit-2522638525.yaml" 16L, 672B[1;1H[34m# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#[m
[36mapiVersion[m[35m:[m v1
[36mdata[m[35m:[m
  [36mSTRIPE_ENDPOINT_SECRET[m[35m:[m d2hzZWNfQnBHa1RqUm9tNVlHdFBiSWgyclhnaVlGeGVJNGJha2M=
  [36mSTRIPE_SECRET_KEY[m[35m:[m c2tfdGVzdF81MVRRQ2JORUhCUlZabWg5ckN4VUVXTU9pSW1veUh2NmZ1dFhUWExSNUQxaUx3Tzc0eDF4ekJTcEtwclh0N3dPVlFwNmJVUGdHd1AA[9;1H4ZXZUM0hBVVJ6UGdFRTAwcXVoejl2VUk=
[36mkind[m[35m:[m Secret
[36mmetadata[m[35m:[m
  [36mcreationTimestamp[m[35m:[m [31m"2026-05-22T21:57:58Z"[m
  [36mname[m[35m:[m payments-secrets
  [36mnamespace[m[35m:[m default
  [36mresourceVersion[m[35m:[m [31m"227649"[m
  [36muid[m[35m:[m b3a02c96-2ced-4c7f-b74a-eafea210677a
[36mtype[m[35m:[m Opaque
[94m~                                                                                                                                   [19;1H~                                                                                                                                   [20;1H~                                                                                                                                   [21;1H~                                                                                                                                   [22;1H~                                                                                                                                   [m[23;115H1,1[11CAll[1;1H[?25h[?4m[23;1H[?2004l[>4;m[23;2t[23;1t[23;1H[K[23;1H[?1004l[?2004l[?1l>[?1049l[23;0;0t[>4;m